server:
  port: 80
  #servlet:
  #  context-path: /z   ,可以多个子目录来区分路径，共存多个应用，但是目前不需要
spring:
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
        keep-alive: 60s
  datasource:
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/note
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1MB
  redis:
    port: 6379
    host: 192.168.11.100
    password: 123456
    database: 1
  mail:
    host: smtp.qq.com #smtp-mail.outlook.com #smtp.office365.com
    port: 587
    username: *********@qq.com
    password: *****  # 邮箱授权码
    properties:
      mail:
        smtp:
          connectiontimeout: 5000  # 连接超时，单位毫秒
          timeout: 30000            # 读超时，单位毫秒
          writetimeout: 30000        # 写超时，单位毫秒
          auth: true
          starttls:
            enable: true
# 滑块验证码
aj:
  captcha:
    # 缓存类型,local或者reids
    cache-type: local # redis #local
    # blockPuzzle 滑块 clickWord 文字点选  default默认两者都实例化
    type: blockPuzzle
    # 校验滑动拼图允许误差偏移量(默认5像素)
    slip-offset: 5
    # aes加密坐标开启或者禁用(true|false)
    aes-status: true
    # 滑动干扰项(0/1/2)
    interference-options: 0
    # 右下角水印
    water-mark: "tangxianglin"

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.tangxianglin.blog.vo,com.tangxianglin.blog.pojo,com.tangxianglin.blog.query
  configuration:
    map-underscore-to-camel-case: true
tom:
  salt: z,'8]3!@~k
  password: 123456
  jwt:
    secure: 123456
    expire: 36000
  aliyunoss:
    endpoint: ********
    access-key-id: ****
    access-key-secret: *****
    bucket-name: webblog-articles-images
articleFiles:
  prepath: mdfiles/
